[package]
name = "sock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.7"
log4rs = "1.1.1"
log = "0.4.17"
clap = {version = "3.1.18", features = ["derive"]}

